INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('ALE', 'ALEMANHA');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('ARG', 'ARGENTINA');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('AUS', 'AUSTRÁLIA');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('BEL', 'BÉLGICA');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('BRA', 'BRASIL');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('CAM', 'CAMARÕES');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('CAN', 'CANADÁ');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('CAT', 'CATAR');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('COR', 'COREIA DO SUL');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('CRI', 'COSTA RICA');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('CRO', 'CROÁCIA');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('DIN', 'DINAMARCA');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('EQU', 'EQUADOR');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('ESP', 'ESPANHA');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('EUA', 'ESTADOS UNIDOS');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('FRA', 'FRANÇA');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('GAL', 'PAIS DE GALES');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('GAN', 'GANA');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('ING', 'INGLATERRA');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('IRA', 'IRÃO');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('JAP', 'JAPÃO');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('MAR', 'MARROCOS');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('MEX', 'MÉXICO');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('PBA', 'PAISES BAIXOS');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('POL', 'POLÓNIA');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('POR', 'PORTUGAL');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('SAU', 'ARABIA SAUDITA');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('SEN', 'SENEGAL');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('SER', 'SÉRVIA');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('SUI', 'SUIÇA');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('TUN', 'TUNISIA');
INSERT INTO `Equipas` (`NomeCurto`, `NomeLongo`) VALUES ('URU', 'URUGUAI');